import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { useTranslation } from "react-i18next";
import { Folder, SieveRule, SieveCondition, SieveAction } from "../types/mail";

interface JmapSieveScript {
  id: string;
  name: string;
  isActive: boolean;
  blobId: string | null;
}

interface Props {
  accountId: string;
  folders: Folder[];
  onClose: () => void;
}

// Helper: Parse Sieve script to rules
function parseSieveScript(content: string): SieveRule[] {
  const rules: SieveRule[] = [];

  let ruleIndex = 0;

  // Try to match rules
  const ruleMatches = content.matchAll(/if\s+(?:allof|anyof)?\s*\(?\s*([^{]+?)\s*\)?\s*\{([^}]+)\}/gi);

  for (const ruleMatch of ruleMatches) {
    const conditionPart = ruleMatch[1].trim();
    const actionPart = ruleMatch[2].trim();

    const conditions: SieveCondition[] = [];
    const actions: SieveAction[] = [];

    // Parse conditions
    // Match: header :contains "From" "value"
    const condPattern = /header\s+:(\w+)\s+"(\w+)"\s+"([^"]+)"/gi;
    let condMatch;
    while ((condMatch = condPattern.exec(conditionPart)) !== null) {
      const operator = condMatch[1].toLowerCase();
      const field = condMatch[2].toLowerCase();
      const value = condMatch[3];
      conditions.push({ field, operator, value });
    }

    // Parse actions
    // fileinto "Folder";
    const fileintoMatch = actionPart.match(/fileinto\s+"([^"]+)"/i);
    if (fileintoMatch) {
      actions.push({ actionType: "fileinto", value: fileintoMatch[1] });
    }

    // redirect "email";
    const redirectMatch = actionPart.match(/redirect\s+"([^"]+)"/i);
    if (redirectMatch) {
      actions.push({ actionType: "redirect", value: redirectMatch[1] });
    }

    // discard;
    if (/discard;/i.test(actionPart)) {
      actions.push({ actionType: "discard" });
    }

    // keep;
    if (/keep;/i.test(actionPart)) {
      actions.push({ actionType: "keep" });
    }

    // addflag
    const flagMatch = actionPart.match(/addflag\s+"([^"]+)"/i);
    if (flagMatch) {
      actions.push({ actionType: "flag", value: flagMatch[1] });
    }

    if (conditions.length > 0 || actions.length > 0) {
      rules.push({
        id: `rule_${ruleIndex++}`,
        name: `Rule ${ruleIndex}`,
        enabled: true,
        conditions: conditions.length > 0 ? conditions : [{ field: "from", operator: "contains", value: "" }],
        actions: actions.length > 0 ? actions : [{ actionType: "keep" }],
      });
    }
  }

  return rules;
}

// Helper: Generate Sieve script from rules
function generateSieveScript(rules: SieveRule[]): string {
  const requires = new Set<string>(["fileinto"]);

  // Check what requires we need
  for (const rule of rules) {
    for (const action of rule.actions) {
      if (action.actionType === "flag") {
        requires.add("imap4flags");
      }
      if (action.actionType === "reject") {
        requires.add("reject");
      }
      if (action.actionType === "vacation") {
        requires.add("vacation");
      }
    }
  }

  let script = `require [${Array.from(requires).map(r => `"${r}"`).join(", ")}];\n\n`;
  script += "# Generated by MailClient\n\n";

  for (const rule of rules) {
    if (!rule.enabled) {
      script += `# Disabled: ${rule.name}\n`;
      continue;
    }

    script += `# ${rule.name}\n`;

    // Build conditions
    const conditions = rule.conditions.map(cond => {
      const field = cond.field.charAt(0).toUpperCase() + cond.field.slice(1);
      return `header :${cond.operator} "${field}" "${cond.value}"`;
    });

    if (conditions.length === 1) {
      script += `if ${conditions[0]}\n`;
    } else {
      script += `if allof (${conditions.join(",\n          ")})\n`;
    }

    script += "{\n";

    // Build actions
    for (const action of rule.actions) {
      switch (action.actionType) {
        case "fileinto":
          script += `    fileinto "${action.value}";\n`;
          break;
        case "redirect":
          script += `    redirect "${action.value}";\n`;
          break;
        case "discard":
          script += "    discard;\n";
          break;
        case "keep":
          script += "    keep;\n";
          break;
        case "flag":
          script += `    addflag "${action.value}";\n`;
          break;
      }
    }

    script += "}\n\n";
  }

  return script;
}

function JmapSieveEditor({ accountId, folders, onClose }: Props) {
  const { t } = useTranslation();
  const [scripts, setScripts] = useState<JmapSieveScript[]>([]);
  const [selectedScript, setSelectedScript] = useState<JmapSieveScript | null>(null);
  const [rules, setRules] = useState<SieveRule[]>([]);
  const [rawScript, setRawScript] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showNewDialog, setShowNewDialog] = useState(false);
  const [newScriptName, setNewScriptName] = useState("");
  const [editingRule, setEditingRule] = useState<SieveRule | null>(null);
  const [showRawEditor, setShowRawEditor] = useState(false);

  useEffect(() => {
    loadScripts();
  }, [accountId]);

  const loadScripts = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await invoke<JmapSieveScript[]>("jmap_list_sieve_scripts", { accountId });
      setScripts(result);
      if (result.length > 0 && !selectedScript) {
        const activeScript = result.find(s => s.isActive) || result[0];
        await selectScript(activeScript);
      }
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  };

  const selectScript = async (script: JmapSieveScript) => {
    setSelectedScript(script);
    if (script.blobId) {
      setLoading(true);
      try {
        const content = await invoke<string>("jmap_get_sieve_script", {
          accountId,
          blobId: script.blobId,
        });
        setRawScript(content);
        setRules(parseSieveScript(content));
      } catch (e) {
        setError(String(e));
        setRawScript("");
        setRules([]);
      } finally {
        setLoading(false);
      }
    } else {
      setRawScript("");
      setRules([]);
    }
  };

  const handleSaveRules = async () => {
    if (!selectedScript) return;
    setSaving(true);
    setError(null);
    try {
      const content = generateSieveScript(rules);
      await invoke("jmap_set_sieve_script", {
        accountId,
        id: selectedScript.id,
        name: selectedScript.name,
        content,
        isActive: selectedScript.isActive,
      });
      setRawScript(content);
      await loadScripts();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleSaveRawScript = async () => {
    if (!selectedScript) return;
    setSaving(true);
    setError(null);
    try {
      await invoke("jmap_set_sieve_script", {
        accountId,
        id: selectedScript.id,
        name: selectedScript.name,
        content: rawScript,
        isActive: selectedScript.isActive,
      });
      setRules(parseSieveScript(rawScript));
      setShowRawEditor(false);
      await loadScripts();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleCreate = async () => {
    if (!newScriptName.trim()) return;
    setSaving(true);
    setError(null);
    try {
      const defaultContent = `require ["fileinto"];\n\n# Generated by MailClient\n`;
      await invoke<string>("jmap_set_sieve_script", {
        accountId,
        id: null,
        name: newScriptName.trim(),
        content: defaultContent,
        isActive: false,
      });
      setNewScriptName("");
      setShowNewDialog(false);
      await loadScripts();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!selectedScript) return;
    if (!confirm(t("sieve.confirmDelete", `Delete script "${selectedScript.name}"?`))) return;

    setSaving(true);
    setError(null);
    try {
      await invoke("jmap_delete_sieve_script", {
        accountId,
        scriptId: selectedScript.id,
      });
      setSelectedScript(null);
      setRawScript("");
      setRules([]);
      await loadScripts();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleActivate = async (script: JmapSieveScript) => {
    setSaving(true);
    setError(null);
    try {
      if (script.isActive) {
        await invoke("jmap_deactivate_sieve_scripts", { accountId });
      } else {
        await invoke("jmap_activate_sieve_script", {
          accountId,
          scriptId: script.id,
        });
      }
      await loadScripts();
    } catch (e) {
      setError(String(e));
    } finally {
      setSaving(false);
    }
  };

  const addRule = () => {
    const newRule: SieveRule = {
      id: `rule_${Date.now()}`,
      name: t("sieve.newRule", "New rule"),
      enabled: true,
      conditions: [{ field: "from", operator: "contains", value: "" }],
      actions: [{ actionType: "fileinto", value: "INBOX" }],
    };
    setEditingRule(newRule);
  };

  const saveRule = () => {
    if (!editingRule) return;
    setRules((prev) => {
      const existing = prev.findIndex((r) => r.id === editingRule.id);
      if (existing >= 0) {
        const updated = [...prev];
        updated[existing] = editingRule;
        return updated;
      } else {
        return [...prev, editingRule];
      }
    });
    setEditingRule(null);
  };

  const deleteRule = (id: string) => {
    setRules((prev) => prev.filter((r) => r.id !== id));
  };

  const toggleRule = (id: string) => {
    setRules((prev) =>
      prev.map((r) => (r.id === id ? { ...r, enabled: !r.enabled } : r))
    );
  };

  // Get folder display names for JMAP
  const getFolderOptions = () => {
    return folders.map(f => {
      const extFolder = f as Folder & { displayName?: string };
      return {
        id: f.name,
        name: extFolder.displayName || f.name,
      };
    });
  };

  return (
    <div className="h-full flex flex-col bg-white">
      {/* Header */}
      <div className="border-b px-4 py-3 flex items-center justify-between">
        <h2 className="text-xl font-semibold text-gray-800">{t("sieve.title")} (JMAP)</h2>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowRawEditor(!showRawEditor)}
            className="px-3 py-1 text-sm text-gray-600 hover:text-gray-800"
          >
            {showRawEditor ? t("sieve.visualEditor", "Visual Editor") : t("sieve.rawScript", "Raw Script")}
          </button>
          <button
            onClick={onClose}
            className="px-3 py-1 text-gray-600 hover:text-gray-800"
          >
            {t("settings.close")}
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-100 border-b border-red-200 px-4 py-2 text-red-700">
          {error}
          <button onClick={() => setError(null)} className="ml-2 text-red-500">
            &times;
          </button>
        </div>
      )}

      <div className="flex-1 flex overflow-hidden">
        {/* Script list */}
        <div className="w-48 border-r p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-sm font-medium text-gray-700">{t("sieve.scripts", "Scripts")}</h3>
            <button
              onClick={() => setShowNewDialog(true)}
              className="text-blue-600 hover:text-blue-800 text-sm"
            >
              + {t("sieve.new", "New")}
            </button>
          </div>
          {loading && scripts.length === 0 ? (
            <div className="text-center text-gray-500 text-sm">{t("common.loading")}</div>
          ) : (
            scripts.map((script) => (
              <div
                key={script.id}
                className={`p-2 rounded cursor-pointer mb-1 flex items-center justify-between ${
                  selectedScript?.id === script.id
                    ? "bg-blue-100 text-blue-800"
                    : "hover:bg-gray-100"
                }`}
                onClick={() => selectScript(script)}
              >
                <span className="text-sm truncate">{script.name}</span>
                {script.isActive && (
                  <span className="text-xs bg-green-500 text-white px-1 rounded">
                    {t("sieve.active")}
                  </span>
                )}
              </div>
            ))
          )}
        </div>

        {/* Main content */}
        <div className="flex-1 p-4 overflow-y-auto">
          {loading ? (
            <div className="flex items-center justify-center h-full">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            </div>
          ) : showRawEditor ? (
            <div className="h-full flex flex-col">
              <textarea
                value={rawScript}
                onChange={(e) => setRawScript(e.target.value)}
                className="flex-1 w-full p-3 border border-gray-300 rounded font-mono text-sm resize-none"
                placeholder="Sieve Script..."
              />
              <div className="mt-3 flex justify-end gap-2">
                <button
                  onClick={() => setShowRawEditor(false)}
                  className="px-4 py-2 text-gray-600 hover:text-gray-800"
                >
                  {t("common.cancel")}
                </button>
                <button
                  onClick={handleSaveRawScript}
                  disabled={saving}
                  className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-blue-400"
                >
                  {saving ? "..." : t("common.save")}
                </button>
              </div>
            </div>
          ) : selectedScript ? (
            <div>
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <h3 className="text-lg font-medium">{selectedScript.name}</h3>
                  {!selectedScript.isActive && (
                    <button
                      onClick={() => handleActivate(selectedScript)}
                      className="text-sm text-blue-600 hover:text-blue-800"
                    >
                      {t("sieve.activate", "Activate")}
                    </button>
                  )}
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={addRule}
                    className="px-3 py-1 bg-green-600 text-white rounded text-sm hover:bg-green-700"
                  >
                    + {t("sieve.rule", "Rule")}
                  </button>
                  <button
                    onClick={handleSaveRules}
                    disabled={saving}
                    className="px-3 py-1 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:bg-blue-400"
                  >
                    {saving ? "..." : t("common.save")}
                  </button>
                  <button
                    onClick={handleDelete}
                    disabled={saving}
                    className="px-3 py-1 bg-red-600 text-white rounded text-sm hover:bg-red-700 disabled:bg-red-400"
                  >
                    {t("common.delete")}
                  </button>
                </div>
              </div>

              {/* Rules list */}
              <div className="space-y-3">
                {rules.map((rule) => (
                  <div
                    key={rule.id}
                    className={`border rounded p-3 ${
                      rule.enabled ? "bg-white" : "bg-gray-50 opacity-60"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={rule.enabled}
                          onChange={() => toggleRule(rule.id)}
                          className="h-4 w-4"
                        />
                        <span className="font-medium">{rule.name}</span>
                      </div>
                      <div className="flex gap-2">
                        <button
                          onClick={() => setEditingRule({ ...rule })}
                          className="text-blue-600 hover:text-blue-800 text-sm"
                        >
                          {t("sieve.editRule", "Edit")}
                        </button>
                        <button
                          onClick={() => deleteRule(rule.id)}
                          className="text-red-600 hover:text-red-800 text-sm"
                        >
                          {t("sieve.deleteRule", "Delete")}
                        </button>
                      </div>
                    </div>
                    <div className="text-sm text-gray-600">
                      <div>
                        <strong>{t("sieve.if", "If")}:</strong>{" "}
                        {rule.conditions.map((c, i) => (
                          <span key={i}>
                            {i > 0 && ` ${t("sieve.and", "AND")} `}
                            {c.field} {c.operator} "{c.value}"
                          </span>
                        ))}
                      </div>
                      <div>
                        <strong>{t("sieve.then", "Then")}:</strong>{" "}
                        {rule.actions.map((a, i) => (
                          <span key={i}>
                            {i > 0 && ", "}
                            {a.actionType}
                            {a.value && ` "${a.value}"`}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}

                {rules.length === 0 && (
                  <div className="text-center text-gray-500 py-8">
                    {t("sieve.noRules", "No rules. Click \"+ Rule\" to create one.")}
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-500">
              {t("sieve.selectOrCreate", "Select a script or create a new one")}
            </div>
          )}
        </div>
      </div>

      {/* Rule Editor Modal */}
      {editingRule && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-lg max-h-[80vh] overflow-y-auto">
            <h3 className="text-lg font-semibold mb-4">{t("sieve.editRule", "Edit Rule")}</h3>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">{t("sieve.ruleName", "Rule Name")}</label>
                <input
                  type="text"
                  value={editingRule.name}
                  onChange={(e) =>
                    setEditingRule({ ...editingRule, name: e.target.value })
                  }
                  className="w-full px-3 py-2 border border-gray-300 rounded"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">{t("sieve.conditions", "Conditions")}</label>
                {editingRule.conditions.map((cond, i) => (
                  <div key={i} className="flex gap-2 mb-2">
                    <select
                      value={cond.field}
                      onChange={(e) => {
                        const newConds = [...editingRule.conditions];
                        newConds[i] = { ...cond, field: e.target.value };
                        setEditingRule({ ...editingRule, conditions: newConds });
                      }}
                      className="px-2 py-1 border border-gray-300 rounded text-sm"
                    >
                      <option value="from">{t("sieve.fieldFrom", "From")}</option>
                      <option value="to">{t("sieve.fieldTo", "To")}</option>
                      <option value="subject">{t("sieve.fieldSubject", "Subject")}</option>
                    </select>
                    <select
                      value={cond.operator}
                      onChange={(e) => {
                        const newConds = [...editingRule.conditions];
                        newConds[i] = { ...cond, operator: e.target.value };
                        setEditingRule({ ...editingRule, conditions: newConds });
                      }}
                      className="px-2 py-1 border border-gray-300 rounded text-sm"
                    >
                      <option value="contains">{t("sieve.opContains", "contains")}</option>
                      <option value="is">{t("sieve.opIs", "is")}</option>
                      <option value="matches">{t("sieve.opMatches", "matches")}</option>
                    </select>
                    <input
                      type="text"
                      value={cond.value}
                      onChange={(e) => {
                        const newConds = [...editingRule.conditions];
                        newConds[i] = { ...cond, value: e.target.value };
                        setEditingRule({ ...editingRule, conditions: newConds });
                      }}
                      className="flex-1 px-2 py-1 border border-gray-300 rounded text-sm"
                      placeholder={t("sieve.valuePlaceholder", "Value...")}
                    />
                    {editingRule.conditions.length > 1 && (
                      <button
                        onClick={() => {
                          const newConds = editingRule.conditions.filter(
                            (_, idx) => idx !== i
                          );
                          setEditingRule({ ...editingRule, conditions: newConds });
                        }}
                        className="text-red-600"
                      >
                        &times;
                      </button>
                    )}
                  </div>
                ))}
                <button
                  onClick={() =>
                    setEditingRule({
                      ...editingRule,
                      conditions: [
                        ...editingRule.conditions,
                        { field: "from", operator: "contains", value: "" },
                      ],
                    })
                  }
                  className="text-sm text-blue-600 hover:text-blue-800"
                >
                  + {t("sieve.addCondition", "Condition")}
                </button>
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">{t("sieve.actions", "Actions")}</label>
                {editingRule.actions.map((action, i) => (
                  <div key={i} className="flex gap-2 mb-2">
                    <select
                      value={action.actionType}
                      onChange={(e) => {
                        const newActions = [...editingRule.actions];
                        newActions[i] = { ...action, actionType: e.target.value };
                        setEditingRule({ ...editingRule, actions: newActions });
                      }}
                      className="px-2 py-1 border border-gray-300 rounded text-sm"
                    >
                      <option value="fileinto">{t("sieve.actionMoveTo", "Move to")}</option>
                      <option value="redirect">{t("sieve.actionRedirect", "Redirect to")}</option>
                      <option value="discard">{t("sieve.actionDiscard", "Discard")}</option>
                      <option value="keep">{t("sieve.actionKeep", "Keep")}</option>
                      <option value="flag">{t("sieve.actionFlag", "Flag")}</option>
                    </select>
                    {(action.actionType === "fileinto" ||
                      action.actionType === "redirect" ||
                      action.actionType === "flag") && (
                      action.actionType === "fileinto" ? (
                        <select
                          value={action.value || ""}
                          onChange={(e) => {
                            const newActions = [...editingRule.actions];
                            newActions[i] = { ...action, value: e.target.value };
                            setEditingRule({ ...editingRule, actions: newActions });
                          }}
                          className="flex-1 px-2 py-1 border border-gray-300 rounded text-sm"
                        >
                          <option value="">{t("sieve.selectFolder", "Select folder...")}</option>
                          {getFolderOptions().map((f) => (
                            <option key={f.id} value={f.id}>
                              {f.name}
                            </option>
                          ))}
                        </select>
                      ) : (
                        <input
                          type="text"
                          value={action.value || ""}
                          onChange={(e) => {
                            const newActions = [...editingRule.actions];
                            newActions[i] = { ...action, value: e.target.value };
                            setEditingRule({ ...editingRule, actions: newActions });
                          }}
                          className="flex-1 px-2 py-1 border border-gray-300 rounded text-sm"
                          placeholder={
                            action.actionType === "redirect"
                              ? "email@example.com"
                              : "Flag..."
                          }
                        />
                      )
                    )}
                    {editingRule.actions.length > 1 && (
                      <button
                        onClick={() => {
                          const newActions = editingRule.actions.filter(
                            (_, idx) => idx !== i
                          );
                          setEditingRule({ ...editingRule, actions: newActions });
                        }}
                        className="text-red-600"
                      >
                        &times;
                      </button>
                    )}
                  </div>
                ))}
                <button
                  onClick={() =>
                    setEditingRule({
                      ...editingRule,
                      actions: [
                        ...editingRule.actions,
                        { actionType: "keep", value: undefined },
                      ],
                    })
                  }
                  className="text-sm text-blue-600 hover:text-blue-800"
                >
                  + {t("sieve.addAction", "Action")}
                </button>
              </div>
            </div>

            <div className="mt-6 flex justify-end gap-2">
              <button
                onClick={() => setEditingRule(null)}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                {t("common.cancel")}
              </button>
              <button
                onClick={saveRule}
                className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
              >
                {t("common.save")}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* New Script Dialog */}
      {showNewDialog && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg shadow-xl p-6 w-96">
            <h3 className="text-lg font-semibold mb-4">{t("sieve.newScript", "New Script")}</h3>
            <input
              type="text"
              value={newScriptName}
              onChange={(e) => setNewScriptName(e.target.value)}
              placeholder={t("sieve.scriptName", "Script name")}
              className="w-full px-3 py-2 border border-gray-300 rounded mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
              autoFocus
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => {
                  setShowNewDialog(false);
                  setNewScriptName("");
                }}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
                disabled={saving}
              >
                {t("common.cancel")}
              </button>
              <button
                onClick={handleCreate}
                disabled={saving || !newScriptName.trim()}
                className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:bg-blue-400"
              >
                {saving ? "..." : t("common.create", "Create")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default JmapSieveEditor;
